### ISSUE TITLE
Volumes & VolumeSnapshots: Rok Annotations & Rok Chooser

### ISSUE THREAD

**Issue by elikatsis** [kubeflow-kale/jupyterlab-kubeflow-kale#2]
### Volumes
Add a special (optional) annotation field for RokURL adding the following annotation to `VolumeOp`:
```yaml
rok/origin: <RokURL>
```

### VolumeSnapshots
Add a special (optional) annotation field for RokURL adding the following annotation to `VolumeSnapshotOp`:
```yaml
rok/register: <RokURL>
```

### Rok Chooser
Integrate Rok Chooser on both of these fields.

**Comment by StefanoFioravanzo** [comment]
@elikatsis what do you think about implementing the annotations as two separate buttons that open the Rok Chooser? When the user chooses a volume from the chooser we can show a label with the resource name below the button.

The annotation buttons can be shown just when a user selects `Existing PVC` in the Volumes select input.

**Comment by elikatsis** [comment]
There should be fields so users can manually write/copy-paste links there. But there also should be a button to open Rok Chooser.

UI should end up having fields similar to this [screenshot from MiniKF JWA's `New Server` page]:
![image](https://user-images.githubusercontent.com/14970053/66586337-1d8bd780-eb91-11e9-9f4a-9b0787719d7a.png)

Moreover, users don't choose _volumes_ via Rok Chooser. They choose _snapshots_ to _clone_ **new** PVCs from.
That means, `rok/origin` is an annotation on a `New Volume` (currently named `New PVC` if I remember correctly).
