### ISSUE TITLE
Update Kale in NPM Lab Extension Repository

### ISSUE THREAD

**Issue by TomLaMantia** [kubeflow-kale/jupyterlab-kubeflow-kale#53]
I would like to run the latest version of this extension (with the metrics tag now added in the UI), but this seems to not be updated on the NPM repo that stores this extension.

Thank you!

**Comment by StefanoFioravanzo** [comment]
@TomLaMantia can I ask you to open this issue in the `kale` repo? I will answer you in details there. I am about to archive this repository as we have moved all the code there. Thanks!
